# SPDX-FileCopyrightText: 2023-2025 Carnegie Mellon University
# SPDX-License-Identifier: 0BSD

[tool.poe.tasks.build]
help = "Build sdist and wheel"
cmd = "uv build"

[tool.poe.tasks.check]
help = "Manually run pre-commit jobs"
sequence = [
    "pre-commit run -a",
    "mypy",
]
default_item_type = "cmd"
ignore_fail = "return_non_zero"

[tool.poe.tasks.protoc]
help = "Regenerate protocol buffer files"
sequence = [
"""
python -m grpc_tools.protoc -I protos
        --python_out=src/hawk/proto
        --mypy_out=src/hawk/proto
        common.proto messages.proto
""", """
sed -i -e 's/import common_pb2 as/from . import common_pb2 as/'
       -e 's/from common_pb2 import/from .common_pb2 import/'
        src/hawk/proto/*_pb2.py src/hawk/proto/*_pb2.pyi
"""
]
default_item_type = "cmd"

[tool.poe.tasks.resolve]
help = "Resolve conflicts on generated code (uv.lock, *_pb2.py)"
sequence = [
    # make sure pyproject.toml and messages.proto are merged
    { cmd = "git diff --check pyproject.toml protos/messages.proto" },
    { cmd = "uv lock" },
    { ref = "protoc" },
    { cmd = "git add uv.lock src/hawk/proto/*_pb2.py*" },
]
