# SPDX-FileCopyrightText: 2023 Carnegie Mellon University
# SPDX-License-Identifier: 0BSD

[tool.poe.tasks.build]
help = "Build sdist and wheel"
cmd = "poetry build"

[tool.poe.tasks.check]
help = "Manually run pre-commit jobs"
sequence = [
    "pre-commit run -a",
    "mypy",
]
default_item_type = "cmd"

[tool.poe.tasks.protoc]
help = "Regenerate protocol buffer files"
cmd = """
python -m grpc_tools.protoc -I protos
        --python_out=src/hawk/proto
        --mypy_out=src/hawk/proto
        messages.proto
"""

[tool.poe.tasks.resolve]
help = "Resolve conflicts on generated code (poetry.lock, *_pb2.py)"
sequence = [
    # make sure pyproject.toml and messages.proto are merged
    { cmd = "git diff --check pyproject.toml protos/messages.proto" },
    { cmd = "poetry lock" },
    { ref = "protoc" },
    { cmd = "git add poetry.lock src/hawk/proto/*_pb2.py*" },
]
