mission-name: "test-hawk" # Mission identifier 
train-location: scout 
label-mode: script # type of labeling interface
scouts: # list of addresses of scouts
- agra.diamond.cs.cmu.edu
- briolette.diamond.cs.cmu.edu
- cullinan.diamond.cs.cmu.edu
  # - dresden.diamond.cs.cmu.edu
  # - indore.diamond.cs.cmu.edu
  # - kimberly.diamond.cs.cmu.edu
  # - patiala.diamond.cs.cmu.edu
  # - transvaal.diamond.cs.cmu.edu
scout-params: # directory on scouts where data, models and logs of mission are saved
  mission_dir: /srv/diamond/dota/delphi/
home-params:
  mission_dir: /home/shilpag/Documents/hawk-data # directory where inbound and outbound data stored @ home
  gt_dir: /srv/diamond/dota/roundabout/labels # directory where labels present
  log_dir: ../../logs
dataset:
  type: random # type of input data
  stream_path: /home/shilpag/dota-exp/datasplit/43/roundabout-43/stream.txt # path on home of stream path
  index_path: /srv/diamond/INDEXES/GIDIDXHAWK # path on scout of index file
  tiles_per_frame: 200 # number of tiles per frame if random sampling
retrain_policy:
  type: percentage # type of retrain condition 
  only_positives: true # if only positives are counted
  threshold: 0.33 # percentage of increment
train_strategy:
  type: dnn_classifier # type of model training
  args:
    arch: resnet50
    batch-size: '64'
    mode: hawk
    online_epochs: '[[10,0],[15,100]]'
    unfreeze_layers: '3'
  bootstrap_path: /srv/diamond/dota/bootstrap-43/roundabout-43.zip
  initial_model_path: /srv/diamond/dota/initial-resnet/roundabout.pth
selector:
  type: topk # type of selective transmission
  topk:
    k: 30
    batchSize: 1000
reexamination:
  type: top # type of reexamination strategy
  k: 100 
bandwidth: 100
