deploy:
  scouts: # list of ssh [user@]host[:port] addresses for scouts
    - hawk@agra.diamond.cs.cmu.edu
    - hawk@briolette.diamond.cs.cmu.edu
    - hawk@cullinan.diamond.cs.cmu.edu
    - hawk@dresden.diamond.cs.cmu.edu
    - hawk@indore.diamond.cs.cmu.edu
    - hawk@kimberly.diamond.cs.cmu.edu
    - host: patiala.diamond.cs.cmu.edu
      user: hawk
      port: 22
      ##deployment_time: jknlnk
      ##model_version: 1


    - host: transvaal.diamond.cs.cmu.edu
      user: hawk
  scout_port: 7700
  #bandwidth:
  #  scout2scout_speed: 1000 # speed in kbit/s
  #  scout2client_speed: 100 # speed in kbit/s
  #  scout2client_delay: 1000 # latency in ms
  #bandwidth: 12k  # bandwidth preset (12k, 30k, 100k, 1M)



## global policy for each type
## global start time: 300
##start on model 3
###
#  default_deploy_scout:
#    start_time: 0
#    on_model: 0
#    mission_duration_percentage: 0
#  default_deploy_home:
#    min_num_scout_destroyed: 0
#    min_num_scouts_remaining: 0
#  per_scout_override:
#    agra:
#    briolette:
#      start_time: 300 ## 5 minutes later
#    cullinan:
#      on_model: 1
#    dresden:
#    kimberly:
#    patiala:
#    indore:
#    transvaal:
