# Change paths to scope cookie and mission_dir
mission-name: "test" # Mission identifier
train-location: scout
label-mode: ui # type of labeling interface
scouts: # list of addresses of scouts
- briolette.diamond.cs.cmu.edu
- cullinan.diamond.cs.cmu.edu
- dresden.diamond.cs.cmu.edu
- indore.diamond.cs.cmu.edu
- kimberly.diamond.cs.cmu.edu
- patiala.diamond.cs.cmu.edu
- transvaal.diamond.cs.cmu.edu
scout-params: # directory on scouts where data, models and logs of mission are saved
  mission_dir: /srv/diamond/dota/delphi/
home-params:
  mission_dir: /path/on/home/hawk-data # directory where inbound and outbound data stored @ home
  log_dir: ../../logs
dataset:
  type: cookie # type of input data
  path: /path/to/.hawk/NEWSCOPE
retrain_policy:
  type: absolute # type of retrain condition
  only_positives: true # if only positives are counted
  threshold: 1000 # percentage of increment
train_strategy:
  type: fsl # type of model training
  example_path: /path/to/.hawk/example.jpg
bandwidth: 100
selector:
  type: topk # type of selective transmission
  topk:
    k: 1
    batchSize: 100
reexamination:
  type: top # type of reexamination strategy
  k: 100
